### ISSUE TITLE
The exact shortest travel time problem

### ISSUE THREAD

**Issue by wangyong01** [GVeitBatz/KaTCH#5]
After testing the code, I found it is a approximate solution, not exact shortest travel time for a query.
But see from the readme, it called TCH, which is exact query.  Is there any misunderstanding?

Thank you for your time.

**Comment by GVeitBatz** [comment]
Hi,
what behaviour did you observe to come to this conclusion? In theory TCH is an exact algorithm. In practice it may suffer from rounding errors (due to floating point arithmetics), but only for large road networks with lots of time-dependency. So what kind of approximative results did you see?
Kind regards, Veit

**Comment by wangyong01** [comment]
Sorry for bother.
But when I use this code on run_tch_ea_query.cpp with demands arrival times generated by TD-Dijkstra, the error of computed arrival time is bigger than 1%. Maybe I have get some misunderstandings on data format or some misunders  on the run_tch_ea_query.cpp in this repos.
